### ISSUE TITLE
Nice work! Any help needed?

### ISSUE THREAD

**Issue by Shoshin23** [LitleCarl/ShowAndTell#1]
Hey! 

Nice work on getting this to coreML. Super useful. Are you already done with training for 100k epochs? I could try to help there if not.

Thanks

**Comment by jcao-ai** [comment]
@Shoshin23 Thanks！
I will attach the Keras model and training data into this repo in several days.

**Comment by Shoshin23** [comment]
Sure! thanks! Neat work. :)

**Comment by jcao-ai** [comment]
@Shoshin23 Keras part has been updated. Pretrained file will be uploaded soon.😄

**Comment by Shoshin23** [comment]
Hey @LitleCarl, 

Thanks for this. I will have access to some google credits in the coming weeks and should be able to train the model upto 100k epochs. I will re-upload the models once i do that.
