### ISSUE TITLE
I have a question about the number of training epoch.

### ISSUE THREAD

**Issue by ANYMS-A** [LitleCarl/ShowAndTell#3]
you trained the model with 40k epochs?if I don't  have a GPU to accelerate the training process, what number of epoh should I set? and I checked your code I find that your total number of epoch is 100,so does that mean you trained the model 400time?

**Comment by jcao-ai** [comment]
sorry, I think there was a typo here. It should be 100k(1,000,000) steps, not epochs. If you don't have a GPU, it should take a lot of time (maybe days or weeks).

**Comment by crissallan** [comment]
Thanks！ Dose the “steps”you said demonstrate the number of mini batch？




| |
胡雅伦
邮箱：allancodeman@163.com
|

签名由 网易邮箱大师 定制

On 03/12/2018 10:04, 曹佳鑫 wrote:

sorry, I think there was a typo here. It should be 100k(1,000,000) steps, not epochs. If you don't have a GPU, it should take a lot of time (maybe days or weeks).

**Comment by jcao-ai** [comment]
@crissallan Yes, batch size is set to 32 by default.
