### ISSUE TITLE
I have a question about the preprocessing of COCO data set?

### ISSUE THREAD

**Issue by ANYMS-A** [LitleCarl/ShowAndTell#4]
Sorry to bother you again ! In the keras_part folder, you did not mention the way you preprocessing the training data into tf.records ,is it the same way as the official model did in https://github.com/tensorflow/models/blob/master/research/im2txt/im2txt/data/build_mscoco_data.py

**Comment by jcao-ai** [comment]
Yes, I just use the tfrecords built by  `im2txt/im2txt/data/build_mscoco_data.py`

**Comment by ANYMS-A** [comment]
Thanks! I think I could do some work about fine-tune base on your work!

**Comment by crissallan** [comment]
Thanks! I think I could do some work about fine-tune base on your work!
